git:
  depth: 10

branches:
  except:
    gh-pages

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7

os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
script:
  - mkdir build && cd build
  - cmake .. -DTESTING=1 -DCMAKE_BUILD_TYPE=Debug
  - make -j
  - CTEST_OUTPUT_ON_FAILURE=1 make test
notifications:
  email: false
sudo: false

after_success: |
  if  [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    if [[ "$CXX" == "g++-4.9" ]]; then
      cd $TRAVIS_BUILD_DIR
      chmod +x generateDocument.sh
      ./generateDocument.sh
      touch docs/.nojekyll
    fi
  fi
  if [[ "$CXX" == "g++-4.9" ]]; then
    CC="gcc"
  fi
  if [[ "$CXX" = "clang++-3.7" ]]; then
    CC="clang"
  fi
  cd $TRAVIS_BUILD_DIR/build

  if [ $TRAVIS_TAG ]; then
    mkdir release && cd release
    cmake ../.. -DCMAKE_BUILD_TYPE=Release
    make -j
    if  [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cp -r ../../src/include ./include
      tar -czvf linux-$CC.tar.gz libcuhkszlib.a include
    else
      tar -cvf macos.tar libcuhkszlib.a
      cd ../../src
      tar -rvf ../build/release/macos.tar include
      cd ../build/release
      tar -cvzf macos-$CC.tar.gz @macos.tar
    fi
  fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch:
      master
    condition: " (( $TRAVIS_OS_NAME = linux ) && ( $CXX = g++-4.9 ) && ($GITHUB_TOKEN))  "
  local_dir: $TRAVIS_BUILD_DIR/docs

deploy:
  skip_cleanup: true
  api_key: $RELEASE_TOKEN
  provider: releases
  file_glob: true
  file: "*.tar.gz"
  on:
    all_branches: true
    condition: " ($TRAVIS_TAG) "
    tag: true
