git:
  depth: 10
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7"
  CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
script:
- mkdir build && cd build
- cmake -DTESTING=1 ..
- make
- CTEST_OUTPUT_ON_FAILURE=1 make test
notifications:
  email: false
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_94acff848013_key -iv $encrypted_94acff848013_iv
  -in travisci_rsa.enc -out ~\/.ssh/travisci_rsa -d
- mv ~/.ssh/travisci_rsa ~/.ss/id_rsa
